version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    container_name: padel_db
    environment:
      POSTGRES_DB: padel
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: padel_backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
  frontend:
    build: ./frontend
    container_name: padel_frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  pgdata:

